apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonflask-deployment
  namespace: stag-workload
  labels:
    app: gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: pythonflask
        image: gcr.io/modified-tome-393216/gcpdevops-stageprj
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: stag-workload
spec:
  selector:
    app: gcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
