apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonflask-deployment
  labels:
    app: gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: pythonflask
        image: gcr.io/modified-tome-393216/gcpdevopsprj
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
